language: php
sudo: false
php:
  - '5.6'
  - '7.1'
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./test/
notifications:
  email: false
